---
name: Deployment Stage
on:
  workflow_dispatch

jobs:
  set-state:
    runs-on: ubuntu-latest
    outputs:
      path_prefix: ${{ steps.get_path_prefix.outputs.path_prefix }}
      branch_short_ref: ${{ steps.get_branch.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get pathPrefix
        uses: actions/github-script@v6
        id: get_path_prefix
        with:
          script: |
            const script = require('./.github/scripts/get-path-prefix.js');
            script({ core });
          result-encoding: string
      - name: Get branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
        id: get_branch

  echo-state:
    needs: [set-state]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repository org - ${{ github.event.repository.owner.login }}"
      - run: echo "Repository name - ${{ github.event.repository.name }}"
      - run: echo "Repository branch - ${{ needs.set-state.outputs.branch_short_ref }}"
      - run: echo "Path prefix - ${{ needs.set-state.outputs.path_prefix }}"


  build:
    defaults:
      run:
        shell: bash
    needs: [set-state]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node v16 for Yarn v3
        uses: actions/setup-node@v3
        with:
          node-version: "16.15.0" # Current LTS version

      - name: Enable Corepack for Yarn v3
        run: corepack enable

      - name: Install Yarn v3
        uses: borales/actions-yarn@v3
        with:
          cmd: set version stable

      - name: Install Dependencies
        uses: borales/actions-yarn@v3
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        with:
          cmd: install

      - name: Build navigation file
        uses: borales/actions-yarn@v3
        with:
          cmd: buildNavigation

      - name: Publish markdown files in ./src/pages
        run: |
            bash .github/scripts/publish-mds-stage.sh "./src/pages" "${{ needs.set-state.outputs.path_prefix }}"
